# Generated by Django 6.0.2 on 2026-04-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_room_utility_rates'),
        ('tenants', '0004_backend_finalization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('courier', models.CharField(choices=[('Kerry', 'Kerry Express'), ('ThaiPost', 'ไปรษณีย์ไทย (ThaiPost)'), ('Shopee', 'Shopee Express'), ('Flash', 'Flash Express'), ('Lazada', 'Lazada Logistics'), ('J&T', 'J&T Express'), ('Ninja', 'Ninja Van'), ('Other', 'อื่นๆ')], default='Kerry', max_length=50)),
                ('parcel_type', models.CharField(choices=[('กล่องใหญ่', 'กล่องใหญ่'), ('กล่องเล็ก', 'กล่องเล็ก'), ('ห่อใหญ่', 'ห่อใหญ่'), ('ห่อเล็ก', 'ห่อเล็ก'), ('ซองใหญ่', 'ซองใหญ่'), ('ซองเล็ก', 'ซองเล็ก'), ('อื่นๆ', 'อื่นๆ')], default='กล่องเล็ก', max_length=50)),
                ('parcel_image', models.ImageField(blank=True, null=True, upload_to='parcels/')),
                ('status', models.CharField(choices=[('pending', 'ค้างรับ'), ('received', 'รับจ่ายแล้ว')], default='pending', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parcels', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='rooms.room')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
