# Generated by Django 6.0.2 on 2026-03-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_meter_billing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['-reading_date', 'room__room_number']},
        ),
        migrations.AlterField(
            model_name='meter',
            name='reading_value',
            field=models.DecimalField(decimal_places=2, help_text='จำนวนหน่วยไฟที่ใช้ในรอบบิลนี้', max_digits=10),
        ),
    ]
