# Generated by Django 6.0.4 on 2026-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_alter_meter_options_alter_meter_reading_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={},
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='water_charge',
            new_name='water_units',
        ),
        migrations.AlterField(
            model_name='meter',
            name='reading_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
