# Generated by Django 6.0.4 on 2026-04-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_alter_meter_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='water_units',
            new_name='water_charge',
        ),
    ]
