# Generated by Django 6.0.2 on 2026-03-31 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_elec', models.FloatField(default=0)),
                ('curr_elec', models.FloatField(default=0)),
                ('prev_water', models.FloatField(default=0)),
                ('curr_water', models.FloatField(default=0)),
                ('reading_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('floor', models.IntegerField(default=1)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('elec_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('water_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='tenant',
        ),
        migrations.AddField(
            model_name='billing',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='service_month',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='meter_reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.meterreading'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.room'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.room'),
        ),
    ]
