# Generated by Django 6.0.2 on 2026-04-09 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_meterreading_room_rename_total_billing_total_amount_and_more'),
        ('rooms', '0003_room_utility_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
