# Generated by Django 6.0.4 on 2026-04-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_billing_room_alter_meterreading_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
