# Generated by Django 6.0.4 on 2026-04-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_billing_paid_date'),
        ('meters', '0005_rename_water_units_meter_water_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='meter_reading',
        ),
        migrations.AddField(
            model_name='billing',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meters.meter'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
