# Generated by Django 6.0.2 on 2026-04-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_backend_finalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='can_confirm_payment',
            field=models.BooleanField(default=False),
        ),
    ]
