# Generated by Django 6.0.2 on 2026-04-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('รายเดือน', 'รายเดือน'), ('รายวัน', 'รายวัน')], default='รายเดือน', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='size_sqm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('ว่าง', 'ว่าง'), ('ไม่ว่าง', 'ไม่ว่าง'), ('ซ่อมบำรุง', 'ซ่อมบำรุง')], default='ว่าง', max_length=20),
        ),
    ]
